# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: assignment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ssignment.proto\x12\nassignment\"O\n\nAssignment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\trubric_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0cinstructions\x18\x04 \x01(\t\"\xc0\x01\n\x06Rubric\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rinstructor_id\x18\x02 \x01(\t\x12?\n\x0frubric_criteria\x18\x05 \x03(\x0b\x32&.assignment.Rubric.RubricCriteriaEntry\x1aR\n\x13RubricCriteriaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.assignment.RubricCriterion:\x02\x38\x01\"J\n\x0fRubricCriterion\x12\x0c\n\x04name\x18\x01 \x01(\t\x12)\n\x06levels\x18\x02 \x03(\x0b\x32\x19.assignment.CriteriaLevel\"3\n\rCriteriaLevel\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assignment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RUBRIC_RUBRICCRITERIAENTRY._options = None
  _RUBRIC_RUBRICCRITERIAENTRY._serialized_options = b'8\001'
  _ASSIGNMENT._serialized_start=32
  _ASSIGNMENT._serialized_end=111
  _RUBRIC._serialized_start=114
  _RUBRIC._serialized_end=306
  _RUBRIC_RUBRICCRITERIAENTRY._serialized_start=224
  _RUBRIC_RUBRICCRITERIAENTRY._serialized_end=306
  _RUBRICCRITERION._serialized_start=308
  _RUBRICCRITERION._serialized_end=382
  _CRITERIALEVEL._serialized_start=384
  _CRITERIALEVEL._serialized_end=435
# @@protoc_insertion_point(module_scope)
