# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grade.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgrade.proto\x12\x05grade\"?\n\rCriteriaGrade\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x11\n\tassesment\x18\x03 \x01(\t\":\n\rGradingMethod\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07githash\x18\x03 \x01(\t\"\xc9\x01\n\x05Grade\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rsubmission_id\x18\x02 \x01(\t\x12\x15\n\rassignment_id\x18\x03 \x01(\t\x12\x11\n\tmethod_id\x18\x04 \x01(\t\x12,\n\x08\x63riteria\x18\x05 \x03(\x0b\x32\x1a.grade.Grade.CriteriaEntry\x1a\x45\n\rCriteriaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.grade.CriteriaGrade:\x02\x38\x01\"\xfe\x01\n\x16\x46\x61\x63ultyGradeAdjustment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rsubmission_id\x18\x02 \x01(\t\x12\x15\n\rassignment_id\x18\x03 \x01(\t\x12\x12\n\nfaculty_id\x18\x04 \x01(\t\x12\x10\n\x08grade_id\x18\x05 \x01(\t\x12=\n\x08\x63riteria\x18\x06 \x03(\x0b\x32+.grade.FacultyGradeAdjustment.CriteriaEntry\x1a\x45\n\rCriteriaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.grade.CriteriaGrade:\x02\x38\x01\"u\n\x17StudentRequestedRegrade\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nstudent_id\x18\x02 \x01(\t\x12\x15\n\rsubmission_id\x18\x03 \x01(\t\x12\x10\n\x08grade_id\x18\x04 \x01(\t\x12\x11\n\treasoning\x18\x05 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grade_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GRADE_CRITERIAENTRY._options = None
  _GRADE_CRITERIAENTRY._serialized_options = b'8\001'
  _FACULTYGRADEADJUSTMENT_CRITERIAENTRY._options = None
  _FACULTYGRADEADJUSTMENT_CRITERIAENTRY._serialized_options = b'8\001'
  _CRITERIAGRADE._serialized_start=22
  _CRITERIAGRADE._serialized_end=85
  _GRADINGMETHOD._serialized_start=87
  _GRADINGMETHOD._serialized_end=145
  _GRADE._serialized_start=148
  _GRADE._serialized_end=349
  _GRADE_CRITERIAENTRY._serialized_start=280
  _GRADE_CRITERIAENTRY._serialized_end=349
  _FACULTYGRADEADJUSTMENT._serialized_start=352
  _FACULTYGRADEADJUSTMENT._serialized_end=606
  _FACULTYGRADEADJUSTMENT_CRITERIAENTRY._serialized_start=280
  _FACULTYGRADEADJUSTMENT_CRITERIAENTRY._serialized_end=349
  _STUDENTREQUESTEDREGRADE._serialized_start=608
  _STUDENTREQUESTEDREGRADE._serialized_end=725
# @@protoc_insertion_point(module_scope)
