# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relationship.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='relationship.proto',
  package='relationship',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12relationship.proto\x12\x0crelationship\"A\n\x16\x41ssignmentAddedToClass\x12\x15\n\rassignment_id\x18\x01 \x01(\t\x12\x10\n\x08\x63lass_id\x18\x02 \x01(\t\"E\n\x1a\x41ssignmentRemovedFromClass\x12\x15\n\rassignment_id\x18\x01 \x01(\t\x12\x10\n\x08\x63lass_id\x18\x02 \x01(\t\";\n\x13StudentAddedToClass\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x10\n\x08\x63lass_id\x18\x02 \x01(\t\"?\n\x17StudentRemovedFromClass\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x10\n\x08\x63lass_id\x18\x02 \x01(\tb\x06proto3')
)




_ASSIGNMENTADDEDTOCLASS = _descriptor.Descriptor(
  name='AssignmentAddedToClass',
  full_name='relationship.AssignmentAddedToClass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='assignment_id', full_name='relationship.AssignmentAddedToClass.assignment_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='class_id', full_name='relationship.AssignmentAddedToClass.class_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=101,
)


_ASSIGNMENTREMOVEDFROMCLASS = _descriptor.Descriptor(
  name='AssignmentRemovedFromClass',
  full_name='relationship.AssignmentRemovedFromClass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='assignment_id', full_name='relationship.AssignmentRemovedFromClass.assignment_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='class_id', full_name='relationship.AssignmentRemovedFromClass.class_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=172,
)


_STUDENTADDEDTOCLASS = _descriptor.Descriptor(
  name='StudentAddedToClass',
  full_name='relationship.StudentAddedToClass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='student_id', full_name='relationship.StudentAddedToClass.student_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='class_id', full_name='relationship.StudentAddedToClass.class_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=233,
)


_STUDENTREMOVEDFROMCLASS = _descriptor.Descriptor(
  name='StudentRemovedFromClass',
  full_name='relationship.StudentRemovedFromClass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='student_id', full_name='relationship.StudentRemovedFromClass.student_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='class_id', full_name='relationship.StudentRemovedFromClass.class_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=298,
)

DESCRIPTOR.message_types_by_name['AssignmentAddedToClass'] = _ASSIGNMENTADDEDTOCLASS
DESCRIPTOR.message_types_by_name['AssignmentRemovedFromClass'] = _ASSIGNMENTREMOVEDFROMCLASS
DESCRIPTOR.message_types_by_name['StudentAddedToClass'] = _STUDENTADDEDTOCLASS
DESCRIPTOR.message_types_by_name['StudentRemovedFromClass'] = _STUDENTREMOVEDFROMCLASS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AssignmentAddedToClass = _reflection.GeneratedProtocolMessageType('AssignmentAddedToClass', (_message.Message,), dict(
  DESCRIPTOR = _ASSIGNMENTADDEDTOCLASS,
  __module__ = 'relationship_pb2'
  # @@protoc_insertion_point(class_scope:relationship.AssignmentAddedToClass)
  ))
_sym_db.RegisterMessage(AssignmentAddedToClass)

AssignmentRemovedFromClass = _reflection.GeneratedProtocolMessageType('AssignmentRemovedFromClass', (_message.Message,), dict(
  DESCRIPTOR = _ASSIGNMENTREMOVEDFROMCLASS,
  __module__ = 'relationship_pb2'
  # @@protoc_insertion_point(class_scope:relationship.AssignmentRemovedFromClass)
  ))
_sym_db.RegisterMessage(AssignmentRemovedFromClass)

StudentAddedToClass = _reflection.GeneratedProtocolMessageType('StudentAddedToClass', (_message.Message,), dict(
  DESCRIPTOR = _STUDENTADDEDTOCLASS,
  __module__ = 'relationship_pb2'
  # @@protoc_insertion_point(class_scope:relationship.StudentAddedToClass)
  ))
_sym_db.RegisterMessage(StudentAddedToClass)

StudentRemovedFromClass = _reflection.GeneratedProtocolMessageType('StudentRemovedFromClass', (_message.Message,), dict(
  DESCRIPTOR = _STUDENTREMOVEDFROMCLASS,
  __module__ = 'relationship_pb2'
  # @@protoc_insertion_point(class_scope:relationship.StudentRemovedFromClass)
  ))
_sym_db.RegisterMessage(StudentRemovedFromClass)


# @@protoc_insertion_point(module_scope)
