# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: artifact.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61rtifact.proto\x12\x08\x61rtifact\"x\n\x12\x41ssignmentArtifact\x12\x14\n\x0cversion_uuid\x18\x01 \x01(\t\x12\x1f\n\x17\x61ssignment_version_uuid\x18\x02 \x01(\t\x12\x10\n\x08\x61rtifact\x18\x03 \x01(\t\x12\x19\n\x11version_timestamp\x18\x04 \x01(\x04\"x\n\x12SubmissionArtifact\x12\x14\n\x0cversion_uuid\x18\x01 \x01(\t\x12\x1f\n\x17submission_version_uuid\x18\x02 \x01(\t\x12\x10\n\x08\x61rtifact\x18\x03 \x01(\t\x12\x19\n\x11version_timestamp\x18\x04 \x01(\x04\"v\n\x11\x43riterionArtifact\x12\x14\n\x0cversion_uuid\x18\x01 \x01(\t\x12\x1e\n\x16\x63riterion_version_uuid\x18\x02 \x01(\t\x12\x10\n\x08\x61rtifact\x18\x03 \x01(\t\x12\x19\n\x11version_timestamp\x18\x04 \x01(\x04\"\x84\x01\n\x16\x43riterionGradeArtifact\x12\x14\n\x0cversion_uuid\x18\x01 \x01(\t\x12\'\n\x1f\x61i_grading_started_version_uuid\x18\x02 \x01(\t\x12\x10\n\x08\x61rtifact\x18\x03 \x01(\t\x12\x19\n\x11version_timestamp\x18\x04 \x01(\x04\"9\n\x0b\x41rtifactLog\x12\x1d\n\x15\x61rtifact_version_uuid\x18\x01 \x01(\t\x12\x0b\n\x03log\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'artifact_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ASSIGNMENTARTIFACT']._serialized_start=28
  _globals['_ASSIGNMENTARTIFACT']._serialized_end=148
  _globals['_SUBMISSIONARTIFACT']._serialized_start=150
  _globals['_SUBMISSIONARTIFACT']._serialized_end=270
  _globals['_CRITERIONARTIFACT']._serialized_start=272
  _globals['_CRITERIONARTIFACT']._serialized_end=390
  _globals['_CRITERIONGRADEARTIFACT']._serialized_start=393
  _globals['_CRITERIONGRADEARTIFACT']._serialized_end=525
  _globals['_ARTIFACTLOG']._serialized_start=527
  _globals['_ARTIFACTLOG']._serialized_end=584
# @@protoc_insertion_point(module_scope)
