# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: assignment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='assignment.proto',
  package='assignment',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x61ssignment.proto\x12\nassignment\"O\n\nAssignment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\trubric_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0cinstructions\x18\x04 \x01(\t\"\xce\x01\n\x06Rubric\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rinstructor_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12?\n\x0frubric_criteria\x18\x04 \x03(\x0b\x32&.assignment.Rubric.RubricCriteriaEntry\x1aR\n\x13RubricCriteriaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.assignment.RubricCriterion:\x02\x38\x01\"V\n\x0fRubricCriterion\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12)\n\x06levels\x18\x03 \x03(\x0b\x32\x19.assignment.CriteriaLevel\"3\n\rCriteriaLevel\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\tb\x06proto3')
)




_ASSIGNMENT = _descriptor.Descriptor(
  name='Assignment',
  full_name='assignment.Assignment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='assignment.Assignment.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rubric_id', full_name='assignment.Assignment.rubric_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='assignment.Assignment.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instructions', full_name='assignment.Assignment.instructions', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=111,
)


_RUBRIC_RUBRICCRITERIAENTRY = _descriptor.Descriptor(
  name='RubricCriteriaEntry',
  full_name='assignment.Rubric.RubricCriteriaEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='assignment.Rubric.RubricCriteriaEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='assignment.Rubric.RubricCriteriaEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=320,
)

_RUBRIC = _descriptor.Descriptor(
  name='Rubric',
  full_name='assignment.Rubric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='assignment.Rubric.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instructor_id', full_name='assignment.Rubric.instructor_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='assignment.Rubric.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rubric_criteria', full_name='assignment.Rubric.rubric_criteria', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RUBRIC_RUBRICCRITERIAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=320,
)


_RUBRICCRITERION = _descriptor.Descriptor(
  name='RubricCriterion',
  full_name='assignment.RubricCriterion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='assignment.RubricCriterion.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='assignment.RubricCriterion.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='levels', full_name='assignment.RubricCriterion.levels', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=408,
)


_CRITERIALEVEL = _descriptor.Descriptor(
  name='CriteriaLevel',
  full_name='assignment.CriteriaLevel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='assignment.CriteriaLevel.score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='assignment.CriteriaLevel.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=461,
)

_RUBRIC_RUBRICCRITERIAENTRY.fields_by_name['value'].message_type = _RUBRICCRITERION
_RUBRIC_RUBRICCRITERIAENTRY.containing_type = _RUBRIC
_RUBRIC.fields_by_name['rubric_criteria'].message_type = _RUBRIC_RUBRICCRITERIAENTRY
_RUBRICCRITERION.fields_by_name['levels'].message_type = _CRITERIALEVEL
DESCRIPTOR.message_types_by_name['Assignment'] = _ASSIGNMENT
DESCRIPTOR.message_types_by_name['Rubric'] = _RUBRIC
DESCRIPTOR.message_types_by_name['RubricCriterion'] = _RUBRICCRITERION
DESCRIPTOR.message_types_by_name['CriteriaLevel'] = _CRITERIALEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Assignment = _reflection.GeneratedProtocolMessageType('Assignment', (_message.Message,), dict(
  DESCRIPTOR = _ASSIGNMENT,
  __module__ = 'assignment_pb2'
  # @@protoc_insertion_point(class_scope:assignment.Assignment)
  ))
_sym_db.RegisterMessage(Assignment)

Rubric = _reflection.GeneratedProtocolMessageType('Rubric', (_message.Message,), dict(

  RubricCriteriaEntry = _reflection.GeneratedProtocolMessageType('RubricCriteriaEntry', (_message.Message,), dict(
    DESCRIPTOR = _RUBRIC_RUBRICCRITERIAENTRY,
    __module__ = 'assignment_pb2'
    # @@protoc_insertion_point(class_scope:assignment.Rubric.RubricCriteriaEntry)
    ))
  ,
  DESCRIPTOR = _RUBRIC,
  __module__ = 'assignment_pb2'
  # @@protoc_insertion_point(class_scope:assignment.Rubric)
  ))
_sym_db.RegisterMessage(Rubric)
_sym_db.RegisterMessage(Rubric.RubricCriteriaEntry)

RubricCriterion = _reflection.GeneratedProtocolMessageType('RubricCriterion', (_message.Message,), dict(
  DESCRIPTOR = _RUBRICCRITERION,
  __module__ = 'assignment_pb2'
  # @@protoc_insertion_point(class_scope:assignment.RubricCriterion)
  ))
_sym_db.RegisterMessage(RubricCriterion)

CriteriaLevel = _reflection.GeneratedProtocolMessageType('CriteriaLevel', (_message.Message,), dict(
  DESCRIPTOR = _CRITERIALEVEL,
  __module__ = 'assignment_pb2'
  # @@protoc_insertion_point(class_scope:assignment.CriteriaLevel)
  ))
_sym_db.RegisterMessage(CriteriaLevel)


_RUBRIC_RUBRICCRITERIAENTRY._options = None
# @@protoc_insertion_point(module_scope)
