# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\"\x91\x01\n\x13\x41ssignmentEmbedding\x12\x14\n\x0cversion_uuid\x18\x01 \x01(\t\x12\x1f\n\x17\x61ssignment_version_uuid\x18\x02 \x01(\t\x12\x15\n\rembedder_uuid\x18\x03 \x01(\t\x12\x11\n\tembedding\x18\x04 \x03(\x02\x12\x19\n\x11version_timestamp\x18\x05 \x01(\t\"\x8f\x01\n\x12\x43riterionEmbedding\x12\x14\n\x0cversion_uuid\x18\x01 \x01(\t\x12\x1e\n\x16\x63riterion_version_uuid\x18\x02 \x01(\t\x12\x15\n\rembedder_uuid\x18\x03 \x01(\t\x12\x11\n\tembedding\x18\x04 \x03(\x02\x12\x19\n\x11version_timestamp\x18\x05 \x01(\t\"\x9a\x01\n\x17\x43riterionGradeEmbedding\x12\x14\n\x0cversion_uuid\x18\x01 \x01(\t\x12$\n\x1c\x63riterion_grade_version_uuid\x18\x02 \x01(\t\x12\x15\n\rembedder_uuid\x18\x03 \x01(\t\x12\x11\n\tembedding\x18\x04 \x03(\x02\x12\x19\n\x11version_timestamp\x18\x05 \x01(\t\"\x91\x01\n\x13SubmissionEmbedding\x12\x14\n\x0cversion_uuid\x18\x01 \x01(\t\x12\x1f\n\x17submission_version_uuid\x18\x02 \x01(\t\x12\x15\n\rembedder_uuid\x18\x03 \x01(\t\x12\x11\n\tembedding\x18\x04 \x03(\x02\x12\x19\n\x11version_timestamp\x18\x05 \x01(\t\"\x8d\x01\n\x11\x41rtifactEmbedding\x12\x14\n\x0cversion_uuid\x18\x01 \x01(\t\x12\x1d\n\x15\x61rtifact_version_uuid\x18\x02 \x01(\t\x12\x15\n\rembedder_uuid\x18\x03 \x01(\t\x12\x11\n\tembedding\x18\x04 \x03(\x02\x12\x19\n\x11version_timestamp\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ASSIGNMENTEMBEDDING']._serialized_start=31
  _globals['_ASSIGNMENTEMBEDDING']._serialized_end=176
  _globals['_CRITERIONEMBEDDING']._serialized_start=179
  _globals['_CRITERIONEMBEDDING']._serialized_end=322
  _globals['_CRITERIONGRADEEMBEDDING']._serialized_start=325
  _globals['_CRITERIONGRADEEMBEDDING']._serialized_end=479
  _globals['_SUBMISSIONEMBEDDING']._serialized_start=482
  _globals['_SUBMISSIONEMBEDDING']._serialized_end=627
  _globals['_ARTIFACTEMBEDDING']._serialized_start=630
  _globals['_ARTIFACTEMBEDDING']._serialized_end=771
# @@protoc_insertion_point(module_scope)
