# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: publish.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpublish.proto\x12\x07publish\";\n\x16RegisterCoursePublicID\x12\x11\n\tpublic_id\x18\x01 \x01(\t\x12\x0e\n\x06lms_id\x18\x02 \x01(\t\"<\n\x17RegisterSectionPublicID\x12\x11\n\tpublic_id\x18\x01 \x01(\t\x12\x0e\n\x06lms_id\x18\x02 \x01(\t\"R\n\x1aRegisterInstructorPublicID\x12\x11\n\tpublic_id\x18\x01 \x01(\t\x12\x0e\n\x06lms_id\x18\x02 \x01(\t\x12\x11\n\tuser_type\x18\x03 \x01(\t\"<\n\x17RegisterStudentPublicID\x12\x11\n\tpublic_id\x18\x01 \x01(\t\x12\x0e\n\x06lms_id\x18\x02 \x01(\t\"?\n\x1aRegisterAssignmentPublicID\x12\x11\n\tpublic_id\x18\x01 \x01(\t\x12\x0e\n\x06lms_id\x18\x02 \x01(\t\";\n\x16RegisterRubricPublicID\x12\x11\n\tpublic_id\x18\x01 \x01(\t\x12\x0e\n\x06lms_id\x18\x02 \x01(\t\"b\n\x1aRegisterSubmissionPublicID\x12\x11\n\tpublic_id\x18\x01 \x01(\t\x12\x19\n\x11lms_assignment_id\x18\x02 \x01(\t\x12\x16\n\x0elms_student_id\x18\x03 \x01(\t\"_\n\x0ePublishedToLMS\x12%\n\x1dpublic_id_of_published_entity\x18\x01 \x01(\t\x12&\n\x1eprivate_id_of_published_entity\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'publish_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERCOURSEPUBLICID._serialized_start=26
  _REGISTERCOURSEPUBLICID._serialized_end=85
  _REGISTERSECTIONPUBLICID._serialized_start=87
  _REGISTERSECTIONPUBLICID._serialized_end=147
  _REGISTERINSTRUCTORPUBLICID._serialized_start=149
  _REGISTERINSTRUCTORPUBLICID._serialized_end=231
  _REGISTERSTUDENTPUBLICID._serialized_start=233
  _REGISTERSTUDENTPUBLICID._serialized_end=293
  _REGISTERASSIGNMENTPUBLICID._serialized_start=295
  _REGISTERASSIGNMENTPUBLICID._serialized_end=358
  _REGISTERRUBRICPUBLICID._serialized_start=360
  _REGISTERRUBRICPUBLICID._serialized_end=419
  _REGISTERSUBMISSIONPUBLICID._serialized_start=421
  _REGISTERSUBMISSIONPUBLICID._serialized_end=519
  _PUBLISHEDTOLMS._serialized_start=521
  _PUBLISHEDTOLMS._serialized_end=616
# @@protoc_insertion_point(module_scope)
