
KAFKA_CONSUMER:
  bootstrap.servers: localhost:9094
  group.id: power_grader_publish_server
  default.topic.config:
    auto.offset.reset: earliest
  enable.auto.commit: true
  auto.commit.interval.ms: 100

KAFKA_PRODUCER:
  bootstrap.servers: localhost:9094
  client.id: power_grader_publish_server
